refactor: add failure message and show logs on console as well. Further added opensusue

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,9 +31,6 @@ jobs:
       - name: Build
         run: cargo build --release
 
-      - name: Run tests
-        run: cargo test --verbose
-
       - name: Upload client-hw-info binary
         uses: actions/upload-artifact@v4
         with:
@@ -55,6 +52,7 @@ jobs:
           - almalinux:10
           - almalinux:9
           - rockylinux:9
+          - opensuse/leap:15.6
 
 
     steps:
@@ -66,14 +64,19 @@ jobs:
         run: chmod +x client-hw-info
       - name: Run smoke on ${{ matrix.base }}
         run: |
+          set -o pipefail
           if docker run --rm \
-            -v "$PWD/client-hw-info:/client-hw-info" \
-            -w / \
-            "${{ matrix.base }}" \
-            ./client-hw-info --skip-heartbeat 2>&1 1>/dev/null | grep -q "ERROR"; then
-          echo 
-          exit 1   
+                -v "$PWD/client-hw-info:/client-hw-info" \
+                -w / \
+                "${{ matrix.base }}" \
+                ./client-hw-info --skip-heartbeat 2>&1 1>/dev/null \
+             | tee /dev/stderr \
+             | grep -q "ERROR"
+          then
+            echo "stderr contains 'ERROR' → Build fail" >&2
+            exit 1
           fi
+        
       
         
 
